import pandas as pd

# Load the metadata from the CSV file generated by gfotos.py
csv_file = "photo_metadata.csv"  # Corrected file name

try:
    # Read the data into a DataFrame
    df = pd.read_csv(csv_file)

    # Ensure the Timestamp column is in datetime format
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='%Y:%m:%d %H:%M:%S')

    # Extract useful information
    df['Hour'] = df['Timestamp'].dt.hour         # Extract the hour
    df['Day'] = df['Timestamp'].dt.day_name()    # Extract the day of the week
    df['Month'] = df['Timestamp'].dt.month_name()  # Extract the month name
    df['Year'] = df['Timestamp'].dt.year         # Extract the year

    # Add a Year-Month column for trend analysis
    df['YearMonth'] = df['Timestamp'].dt.to_period('M')

    # Print the analyzed data
    print("Analyzed Data:")
    print(df.head())  # Display the first few rows of the DataFrame

    print("\nSummary Statistics:")
    print(df.describe(include='all'))  # Include non-numeric stats

    print("\nPhoto Counts by Hour:")
    print(df['Hour'].value_counts())

    print("\nPhoto Counts by Day of the Week:")
    print(df['Day'].value_counts())

    print("\nPhoto Counts by Month:")
    print(df['Month'].value_counts())

    print("\nPhoto Counts by Year:")
    print(df['Year'].value_counts())

except FileNotFoundError:
    print(f"Error: {csv_file} not found. Please run gfotos.py to generate the file.")
except Exception as e:
    print(f"An error occurred: {e}")
